services:
  # Azure Storage Emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite

    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  # Azure Functions project
  functions-app:
    build:
      context: .
      dockerfile: CoffeeNChill_Ice_Task4/Dockerfile
    image: st10472389/coffenchillapi:latest
    container_name: poe-coffee-n-chill
    ports:
      - "80:80"
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCS_WORKER_RUNTIME=dotnet-isolated
    restart: always
